### ISSUE TITLE
Reversed Grav Comp in teach and play example

### ISSUE THREAD

**Issue by Kelym** [HebiRobotics/hebi-python-examples#22]
The grav comp for the `teach_play.py` example in `kits/arm/` uses grav comp computed from `def get_effort` defined in `kits/arm/components/arm_container.py`. But the grav comp computed is reversed to what 5DOF arm / 6DOF arm should use. See [code](https://github.com/HebiRobotics/hebi-python-examples/blob/ff9a8c34a1de2208cea45feddf61e284aae669c5/kits/arm/components/arm_container.py#L47)

Is this the desired behavior? If so we should at least put a comment.

**Comment by rLinks234** [comment]
@Kelym , Sorry for the delay. Most of the office was out on holiday last week. I am looking into this now and will follow up once I investigate this.

**Comment by iamtesch** [comment]
After further diagnosis, it appears this was due to a misconfiguration of zero positions in the arm in question; the teach/repeat grav comp sign is correct in the repo.  I'll go ahead and close this now.
