### ISSUE TITLE
iter() returned non-iterator of type 'EntryList'

### ISSUE THREAD

**Issue by Maxx84** [HebiRobotics/hebi-python-examples#26]
It seems like the basic example 01a_lookup.py is now only working with python3.

When calling

```
for entry in lookup.entrylist:
	print(entry)
```

with python2, I get the following error:

`iter() returned non-iterator of type 'EntryList'`

This was working on hebi-py 0.99.2.

**Comment by rLinks234** [comment]
Hi Maxx84,

I am aware of this issue and am preparing a solution for this in the next release of the Python API. Do note that Python 2.7 is due for end of life starting in [2020](https://pythonclock.org/), so we will only officially support Python 2 for the rest of the year.

**Comment by rLinks234** [comment]
We are sorry for any inconveniences, but we have dropped Python 2.x support starting with `hebi-py` version `1.1.0`. If you need Python 2 support in the time being, you will have to use version `1.0.2`.
